### ISSUE TITLE
Non-DI instantiation of HttpContextAccessor

### ISSUE THREAD

**Issue by lonix1** [intility/serilog-enrichers-azureclaims#13]
Nice library!

Is this safe:

https://github.com/intility/serilog-enrichers-azureclaims/blob/c4ffee4754187cd3e9c88221aa41a014f1790469/src/Serilog.Enrichers.Claims/Enrichers/ClaimEnricher.cs#L46-L46

Surely it should be injected by DI?

**Comment by loekensgard** [comment]
I'm actually not sure, @lonix1.

I shamelessly borrowed the setup from [Serilog.Ernichers.ClientInfo](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/blob/master/src/Serilog.Enrichers.ClientInfo/Enrichers/ClientHeaderEnricher.cs). 

I have used it in many projects over the past year without any noticeable disadvantages, and all my logs are enriched with the desired properties. 

If you would like to enhance the code, a pull request would be greatly appreciated 😄
